app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: password
    pool-size: 30
#app:
 # datasource:
  #  jdbc-url: jdbc:postgresql://ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/d6nqm7fdmjab4b
   # username: hmcnozvatksrzt
    #password: 8987713f4c66ecf430b76ea14692e4152644d54b8a7fb10b6a56822027203879
    #pool-size: 20